spring:
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

gemini:
  api-key: ${GEMINI_API_KEY}
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
